### ISSUE TITLE
repozitar-test.cesnet.cz

### ISSUE THREAD

**Issue by mirekys** [oarepo/oarepo#25]
### 📉  Deployment a monitoring
- [x] build a deployment v cesnetu
- [ ] monitoring uloh na pozadi #3 
- [x] reporting chyb do Sentry #21 

### 📥  Datove modely / Import dat
- [x] prevod fieldu v `oarepo-rdm-records` modelu obsahujicich slovnikove hodnoty (viz [invenio-rdm-records](https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/vocabularies)) na taxonomy typ @Alzpeta 
- [ ] sanitizace html v abstraktu/descriptions vsech recordu v marshmallow @Alzpeta 
- [x] skript pro import taxonomii z CSV slovniku v [invenio-rdm-records](https://github.com/inveniosoftware/invenio-rdm-records/tree/master/invenio_rdm_records/vocabularies) @Alzpeta 
- [x] pro kolekci `articles` pouzit `oarepo-documents` data model @Alzpeta 
- [x] pro kolekci `articles` pouzit stejny recid_v2 minter a fetcher (podobne jako je v `datasets`) @Alzpeta 
- [x] draftovy article record obsahuje v referenced data odkaz na dataset (jeho PID a link na metadata) [oarepo-documents/#9](https://github.com/oarepo/oarepo-documents/issues/9) @Alzpeta 

### 🛠️  Administrace
- [x] administrace taxonomii

### 👾  Bugy & problemy
- [x] [mapping](https://github.com/oarepo/oarepo-rdm-records/blob/master/oarepo_rdm_records/included_mappings/v7/dataset-v1.0.0.json#L159-L161) datasetu ma jiny typ nez je v jsonschema @mirekys 

### 🔐  Security
- [ ] clanek muze vytvorit jen:
  * kurator/admin
  * vlastnik datasetu, na ktery se clanek odkazuje @mirekys

**Comment by mirekys** [comment]
Repozitar-test no longer running
